import Head from "next/head";
import styles from "../../styles/Login.module.css";
import {
  Grid,
  CssBaseline,
  Box,
  Typography,
  Container,
  TextField,
} from "@mui/material";
import Image from "next/image";
import whaleLogo from "../../public/whale.png";
import Button from "../../components/fields/base/Button";
import { useFormik } from "formik";
import * as Yup from "yup";
import { useRouter } from "next/router";

export default function Home() {
  const router = useRouter();

  const LoginSchema = Yup.object().shape({
    userId: Yup.string().required("Required"),
    password: Yup.string().required("Required"),
  });

  // const validate = (values) => {
  //   const errors = {};
  //   if (!values.userId) {
  //     errors.userId = "Required";
  //   } else if (values.userId.length <= 3) {
  //     errors.userId = "User is too short";
  //   }

  //   if (!values.password) {
  //     errors.password = "Required";
  //   } else if (values.password.length <= 3) {
  //     errors.password = "Password is too short";
  //   }
  //   return errors;
  // };

  const formik = useFormik({
    initialValues: {
      userId: "",
      password: "",
    },
    validationSchema: LoginSchema,
    onSubmit: (values) => {
      console.log(values);
      router.push("/dashboard");
    },
  });

  return (
    <div>
      <Head>
        <title>BlueWhale - Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/whaleLogo.png" />
      </Head>

      <main className={styles.main}>
        <Grid container>
          <Grid item xs={12} sm={8} md={6} lg={4} className={styles.left}>
            <Container
              component="main"
              maxWidth="xs"
              type="form"
              onSubmit={formik.handleSubmit}
            >
              <CssBaseline />
              <Box
                sx={{
                  marginTop: 8,
                  display: "flex",
                  flexDirection: "column",
                  alignItems: "center",
                }}
              >
                <Typography component="h1" variant="h5">
                  Sign in
                </Typography>
                <Box sx={{ mt: 1 }} width="90%">
                  <form>
                    <TextField
                      name="userId"
                      label="userID"
                      onChange={formik.handleChange}
                      value={formik.values.userId}
                      size="small"
                      fullWidth
                      type="text"
                      margin="normal"
                      variant="standard"
                      autoFocus
                    />
                    {formik.errors.userId ? (
                      <small>
                        <b style={{ color: "red" }}>{formik.errors.userId}</b>
                      </small>
                    ) : null}
                    <TextField
                      name="password"
                      label="Password"
                      onChange={formik.handleChange}
                      value={formik.values.password}
                      fullWidth
                      size="small"
                      margin="normal"
                      type="password"
                      variant="standard"
                    />
                    {formik.errors.password ? (
                      <small>
                        <b style={{ color: "red" }}>{formik.errors.password}</b>
                      </small>
                    ) : null}
                    <Button onClick={formik.handleSubmit} type="submit">
                      Sign In
                    </Button>
                    Check server status
                  </form>
                </Box>
              </Box>
            </Container>
          </Grid>
          <Grid item xs={0} sm={4} md={6} lg={8} className={styles.right}>
            <footer className={styles.footer}>
              <div>
                <Image
                  src={whaleLogo}
                  priority="1"
                  alt="Picture of the author"
                  width={100}
                  height={100}
                />
              </div>
              <small>
                <b>BlueWhale ERP System</b>
              </small>
            </footer>
          </Grid>
        </Grid>
      </main>
    </div>
  );
}
