import Head from "next/head";
import React from "react";
import NavigationBar from "../../components/navigation/Navbar";
import styles from "../../styles/Dashboard.module.css";

const Dashboard = () => {
  return (
    <div>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/whaleLogo.png" />
      </Head>

      <main className={styles.main}>
        <NavigationBar />
      </main>
    </div>
  );
};

export default Dashboard;
